import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import vm from 'node:vm'
import { Context } from '@deepseek-ai/cordis'
import { agentEvents, installModelSelection, type Agent, type ModelSelectionRef, type PreStepDecision } from '@deepseek-ai/dsh-agent'
import { createUserMessage, ReasoningEffortId, type LlmCallConfig, type UserMessage } from '@deepseek-ai/dsh-llm'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import { describe, expect, it, vi } from 'vitest'

const previous = { provider: 'enterprise', model: 'bisheng:1' }
const selected = { provider: 'enterprise', model: 'bisheng:5' }

async function setup() {
  const ctx = new Context()
  await ctx.plugin(SystemPrompt)
  const names = new Map([['bisheng:1', 'DeepSeek V3'], ['bisheng:5', '阿里云百炼 / Kimi K3']])
  const resolve = vi.fn(async (provider: string, model: string) => ({ provider, id: model, name: names.get(model) ?? model }))
  ctx.provide('llm', {
    resolveModelInfo: resolve,
    listProviders: () => [{ id: 'enterprise', name: '企业模型' }, { id: 'personal', name: '个人模型' }]
  })
  const selection: ModelSelectionRef = { current: selected, assembled: undefined }
  const dispose = installModelSelection(ctx, selection)
  const agent = { session: { requestHeader: () => ({ config: previous }) } } as unknown as Agent
  const signal = new AbortController()
  const message = createUserMessage({ content: [{ type: 'text', text: '继续' }], source: { kind: 'user' } })
  const enter = async (decision: PreStepDecision = { kind: 'enter', messages: [message] }) => {
    await ctx.systemPrompt.assemble()
    return agentEvents(ctx, agent).waterfall('agent/pre-step', {
      turn: 2, step: 1, signal: signal.signal, messages: [message]
    }, async () => decision)
  }
  return { ctx, selection, agent, signal, names, resolve, enter, async close() { dispose(); await ctx.fiber.dispose() } }
}

function notice(result: PreStepDecision): UserMessage {
  if (result.kind !== 'enter' || result.messages.length !== 2) throw new Error('Expected admitted prompt and model notice')
  return result.messages[1]!
}

describe('model switch display names in the installed Harness', () => {
  it('snapshots catalog names in history and keeps request routing on stable IDs', async () => {
    const run = await setup()
    try {
      const message = notice(await run.enter())
      expect(message.source).toMatchObject({ plugin: 'model-selection', summary: 'DeepSeek V3 → 阿里云百炼 / Kimi K3' })
      expect(message.content).toEqual([{ type: 'text', text: '[model changed: assistant turns above this point were generated by DeepSeek V3; the session continues with 阿里云百炼 / Kimi K3]' }])
      const persisted = JSON.parse(JSON.stringify(message))
      run.names.set('bisheng:1', 'Renamed')
      run.names.delete('bisheng:5')
      expect(persisted).toEqual(message)
      const config = await agentEvents(run.ctx, run.agent).waterfall('agent/request', {
        turn: 2, step: 1, signal: run.signal.signal
      }, async (): Promise<LlmCallConfig> => previous)
      expect(config).toMatchObject(selected)
    } finally { await run.close() }
  })

  it('uses provider names across providers and disambiguates equal model names', async () => {
    const run = await setup()
    try {
      run.selection.current = { ...selected, provider: 'personal' }
      expect(notice(await run.enter()).source).toMatchObject({ summary: '企业模型 / DeepSeek V3 → 个人模型 / 阿里云百炼 / Kimi K3' })
      run.selection.current = selected
      run.names.set('bisheng:5', 'DeepSeek V3')
      expect(notice(await run.enter()).source).toMatchObject({ summary: 'DeepSeek V3 (bisheng:1) → DeepSeek V3 (bisheng:5)' })
    } finally { await run.close() }
  })

  it('retains a retired route ID when its metadata is unavailable and admits the next model', async () => {
    const run = await setup()
    try {
      run.resolve.mockRejectedValueOnce(new Error('Previous model was removed'))
      expect(notice(await run.enter()).source).toMatchObject({ summary: 'bisheng:1 → 阿里云百炼 / Kimi K3' })
      run.resolve.mockRejectedValue(new Error('Catalog unavailable'))
      expect(notice(await run.enter()).source).toMatchObject({ summary: 'bisheng:1 → bisheng:5' })
    } finally { await run.close() }
  })

  it('preserves no-request, rejected and reasoning-only steps without fetching metadata', async () => {
    const run = await setup()
    try {
      expect(await run.enter({ kind: 'reject' })).toEqual({ kind: 'reject' })
      expect(await run.enter({ kind: 'enter', messages: [] })).toEqual({ kind: 'enter', messages: [] })
      run.selection.current = { ...previous, reasoningEffort: ReasoningEffortId('high') }
      const result = await run.enter()
      expect(result.kind === 'enter' && result.messages.length).toBe(1)
      expect(run.resolve).toHaveBeenCalledTimes(0)
    } finally { await run.close() }
  })

  it('honors cancellation while resolving names', async () => {
    const run = await setup()
    try {
      run.resolve.mockImplementation(async (provider, model) => {
        run.signal.abort()
        return { provider, id: model, name: 'Resolved' }
      })
      const result = await run.enter()
      expect(result.kind === 'enter' && result.messages.length).toBe(1)
    } finally { await run.close() }
  })
})

type Element = { type: unknown; props: Record<string, unknown> }
type RowProps = { source: UserMessage['source']; content: UserMessage['content']; form: string | null; provenance: { role: string; label: string | null }; t: (key: string) => string }
type BrowserExports = { row: (props: RowProps) => Element; zh: Record<string, string>; en: Record<string, string> }

function browserChat() {
  const require = createRequire(import.meta.url)
  const source = readFileSync(require.resolve('@deepseek-ai/dsh-client-ui-chat').replace(/index\.js$/, 'client.js'), 'utf8')
  let result!: BrowserExports
  // Expose the private row at the bundle boundary; execute its real context dispatch and locales.
  const instrumented = source.replace('return module.exports;', 'return { row: ContextInjectionRow, zh, en };')
  vm.runInNewContext(instrumented, {
    window: { __ModuleLoader__: { load(definition: { factory: (require: (id: string) => unknown) => BrowserExports }) {
      result = definition.factory((id) => {
        if (id === 'react') return { ...require(id), useState: () => [false, vi.fn()] }
        if (id === '@deepseek-ai/dsh-client-ui-primitives' || id === '@deepseek-ai/dsh-client-store') return {}
        return require(id)
      })
    } } }
  })
  return result
}

describe('model switch conversation row', () => {
  it.each(['zh', 'en'] as const)('renders the durable model names with a localized title in %s', async (locale) => {
    const run = await setup()
    try {
      const message = JSON.parse(JSON.stringify(notice(await run.enter()))) as UserMessage
      const browser = browserChat()
      const row = browser.row({ ...message, form: 'notice', provenance: { role: 'injection', label: 'model-selection' }, t: key => browser[locale][key]! })
      expect(row.props.title).toBe(locale === 'zh' ? '已切换模型' : 'Model changed')
      expect((row.props.collapsedContent as Element).props.children).toBe('DeepSeek V3 → 阿里云百炼 / Kimi K3')
      expect((row.props.children as Element).props.children).toBe(browser[locale]['message.modelChangedDetails'])
    } finally { await run.close() }
  })

  it('keeps other context notices and malformed model notices on the generic renderer', () => {
    const browser = browserChat()
    for (const source of [{ kind: 'plugin', plugin: 'skill-catalog', form: 'notice', summary: 'Loaded skills' }, { kind: 'plugin', plugin: 'model-selection' }] as const) {
      const row = browser.row({ source, content: [], form: source.form ?? null, provenance: { role: 'injection', label: source.plugin }, t: key => browser.zh[key]! })
      expect(row.props.title).toBe('上下文注入')
    }
  })
})
