import { SafeXmlNode } from '../../parser/XmlParser';
import { RenderContext } from '../RenderContext';
import type { ChartLineStyle, DataPointStyle } from './types';
export declare function resolveColorToHex(fillNode: SafeXmlNode, ctx: RenderContext): string | undefined;
export declare function extractSeriesColor(ser: SafeXmlNode, ctx: RenderContext): string | object | undefined;
export declare function extractSeriesLineWidth(ser: SafeXmlNode): number | undefined;
export declare function markerSizeToPx(sizePt: number): number;
export declare function extractSeriesLineNoFill(ser: SafeXmlNode): boolean;
export declare function extractChartLineStyle(ln: SafeXmlNode, ctx: RenderContext): ChartLineStyle | undefined;
export declare function extractDataPointStyles(ser: SafeXmlNode, ctx: RenderContext): (DataPointStyle | undefined)[] | undefined;
