import fs from 'node:fs/promises';
const d=JSON.parse(await fs.readFile(office.inputs[0],'utf8'));
const {Document,Paragraph,TextRun,HeadingLevel,Table,TableRow,TableCell,WidthType,BorderStyle,AlignmentType,VerticalAlign,ImageRun,Header,Footer,PageNumber,ExternalHyperlink,Packer}=docx;
const font='Noto Sans CJK SC',ink='20252B',muted='647180',navy='234C68';
const p=(text,opts={})=>new Paragraph({spacing:{after:110,line:300},children:[new TextRun({text,font,size:21,color:ink})],...opts});
const h=(text,level=1,pageBreakBefore=false)=>new Paragraph({text,heading:level===1?HeadingLevel.HEADING_1:HeadingLevel.HEADING_2,pageBreakBefore,keepNext:true,spacing:{before:level===1?170:150,after:125}});
const note=text=>p(text,{spacing:{after:120,line:270},children:[new TextRun({text,font,size:17,color:muted})]});
const fig=async(n,caption,source)=>[p(caption,{keepNext:true,children:[new TextRun({text:caption,font,bold:true,size:20,color:ink})],spacing:{before:100,after:80}}),new Paragraph({children:[new ImageRun({type:'png',data:await fs.readFile(office.inputs[n]),transformation:{width:648,height:215},altText:{title:caption,description:source,name:`图 ${n}`}})],spacing:{after:60}}),note(source)];
const widths=[2200,2200,2200,2200];
function table(rows,ws){const w=ws??rows[0].map(()=>Math.floor(9760/rows[0].length));const border={style:BorderStyle.SINGLE,size:4,color:'D9D9D9'};return new Table({width:{size:9760,type:WidthType.DXA},columnWidths:w,rows:rows.map((row,i)=>new TableRow({tableHeader:i===0,cantSplit:true,children:row.map((text,j)=>new TableCell({width:{size:w[j],type:WidthType.DXA},margins:{top:90,bottom:90,left:110,right:110},verticalAlign:VerticalAlign.CENTER,borders:{top:border,bottom:border,left:border,right:border},shading:{fill:i===0?navy:i%2?'FFFFFF':'F3F6F8'},children:[new Paragraph({spacing:{after:0,line:275},children:[new TextRun({text:String(text),font,size:18,bold:i===0,color:i===0?'FFFFFF':ink})]})]}))}))});}
const children=[];
children.push(note('消费零售研究    2024 年度观察'),new Paragraph({text:d.title,heading:HeadingLevel.TITLE,spacing:{before:80,after:140}}),p('连锁网络扩张与门店经营质量分化',{spacing:{after:200},children:[new TextRun({text:'连锁网络扩张与门店经营质量分化',font,size:26,color:'000000'})]}));
children.push(p('研究结论：2024 年现制咖啡的供给继续扩张，成熟门店的销售表现承受压力。对于准备进入新商圈的经营者，门店数量只能说明网络规模，选址判断还需要同时观察同店销售、价格实现和门店贡献。本报告围绕瑞幸、星巴克中国与 Tims 中国的公开披露，分析竞争结构，并提出可验证的进入假设。'));
children.push(table([['瑞幸集团门店','星巴克中国门店','Tims 中国门店'],['22,340 家','7,596 家','1,022 家']],[3250,3250,3260]),note('数据日期：瑞幸与 Tims 为 2024-12-31；星巴克为 2024-09-29。瑞幸集团含海外门店。[1][2][3]'));
children.push(...await fig(1,'图 1  两家连锁企业的门店网络扩张速度','来源：[1][3]，按披露门店数量计算；基期为 2023 年末。指数用于比较增速，品牌样本代表各自披露范围。'));
children.push(p('核心判断：扩店能够增加覆盖面，但新店贡献、老店分流与促销折让需要分开核算。对中小品牌而言，先验证高频场景中的复购和履约能力，再决定网点密度，更有利于控制试错成本。'),note('阅读路径：供给结构 02 · 经营质量 03 · 消费场景 04 · 店效测算 05 · 市场进入 06 · 资料与方法 07'));
children.push(h('02 供给结构与品牌覆盖',1,true));
children.push(p('门店网络是现制咖啡竞争的重要基础：更短的取餐距离和更密的配送覆盖，可以提高用户在通勤、办公等场景中的可达性。网络扩张也会改变同一品牌内部的客流分配。因此，本节把“门店存量”和“门店增速”放在一起观察，后续再检验经营质量。'));
children.push(...await fig(2,'图 2  三家企业披露的门店规模','来源：[1][2][3]。地域范围及日期存在差异，图中数量用于认识竞争量级，未据此计算中国市场份额。'));
children.push(h('扩张方式影响总部收入与门店经营的关系',2));
children.push(p('瑞幸 2024 年末包含 14,591 家自营门店和 7,749 家联营门店；Tims 年末的 1,022 家门店中，576 家为直营、446 家为加盟。[1][3] 对直营体系，总部直接承担门店租金、人员和经营波动；对于加盟体系，总部收入还受供货、服务费和开店节奏影响。直接比较两类企业的收入除以门店数，容易混淆业务模式。'));
children.push(table([['观察维度','网络扩张提供的信息','仍需补充的证据'],['门店数量','覆盖范围与供给密度','商圈客流、营业时长、净新增与关闭'],['经营模式','直营与加盟的责任分配','总部确认收入与终端零售额的关系'],['单店产出','门店经营的变化方向','开业月份、店龄、面积和渠道结构']],[1900,3500,4360]));
children.push(p('对市场进入的启示：更适合采用商圈层面的竞争清单。将步行范围内的同类品牌、价格实现、营业时段和取餐条件逐一记录，再评估需求是否足以支持新增供给。全国门店排名可以帮助识别重点对手，具体选址仍需落到本地交易条件。'));
children.push(h('03 同店销售与经营质量',1,true));
children.push(p('同店销售为观察既有门店提供了比总收入更接近经营底盘的视角。瑞幸和 Tims 的 2024 年直营同店销售同比均出现负增长，但季度路径存在差异。下图显示，扩张中的品牌仍需持续处理价格、频次与门店间客流分配的问题。[1][3]'));
children.push(...await fig(3,'图 3  直营同店销售的季度变化','来源：[1][3]。两家企业各自采用披露定义；图中呈现方向与幅度，跨品牌水平比较需保留统计定义差异。'));
children.push(h('区分价格变化与交易次数变化',2));
children.push(p('星巴克中国截至 2024 年 9 月 29 日的财季，同店销售同比下降 14%，交易次数下降 6%，客单价下降 8%。[2] 这说明只看销售额会遗漏两个不同的问题：用户来得更少，以及每次支付更少。对运营而言，两者对应的调查和改进动作不同。该财季与自然年第四季度并不重合，应单独阅读。'));
children.push(table([['变化来源','优先追踪指标','可验证的问题'],['价格实现','券后实收、折扣率、渠道佣金','促销新增了交易，还是主要补贴原有购买'],['交易频次','同一用户的周购买次数','习惯形成后，购买是否仍依赖优惠触达'],['渠道迁移','堂食、自取、配送的贡献','新渠道增长能否覆盖其增加的履约成本']],[1700,3800,4260]));
children.push(p('瑞幸第一季度披露同时提到季节性、平均售价下降与竞争因素。[4] 因此，季度回升可以作为继续跟踪的信号，解释时还需要对照促销强度、天气和店龄结构。市场进入决策应观察多个交易周期，避免把短期修复外推成长期增速。'));
children.push(h('04 消费场景与需求假设',1,true));
children.push(p('公开财务数据可以说明企业经营表现，却难以直接还原消费者为什么选择某一家门店。下列场景拆分属于本报告提出的调研框架，用于规划后续访谈和商圈观察。每项判断都需要通过具体用户行为验证，样本企业的数据不替代消费者调查。'));
children.push(table([['场景','核心任务','应验证的需求','建议观察方式'],['早间通勤','在有限时间内买到饮品','出杯稳定性、取餐距离、早餐搭配','工作日早高峰观察与取餐计时'],['办公补给','规律购买且方便送达','实收价格、拼单、配送准确性','同一用户连续两周购买记录'],['社交会面','停留与交流','座位、噪声、清洁和停留体验','分时段座位使用与离店访谈'],['周末休闲','体验与尝新','产品差异、空间、轻食选择','新品复购与完整订单组成']],[1550,2000,3000,3210]));
children.push(h('产品组合需要服务具体时段',2));
children.push(p('Tims 在年度披露中强调咖啡与现制食品的组合。[3] 这一思路提示经营者：饮品之外的产品能否增加交易价值，需要与相应时段一起检验。早餐加购可能提高订单金额，也可能延长出餐时间。比较时应同时记录加购率、制作时间和损耗，避免只优化名义客单价。'));
children.push(p('对于办公场景，可以先拆解工作日频次和配送履约。消费者是否愿意从另一家品牌切换，可能取决于可达性、配送确定性和稳定实收价。调研中应记录实际支付凭证和最近一次购买，而不是仅询问“喜欢什么品牌”。这样更容易区分真实行为与泛泛偏好。'));
children.push(h('用户分层采用行为变量',2));
children.push(p('可按周购买频次、主要购买时段、主要渠道与价格敏感程度形成行为分层。每层至少保留一个可以验证的进入条件，例如工作日复购、配送准时率或无券购买比例。年龄、收入等背景变量可以辅助解释，但单独依靠人口特征很难推导店型和产品组合。'));
children.push(p('访谈建议采用定向探索样本，并同步记录招募渠道。对某一商圈得到的观察，先用于该商圈的经营假设。若要推断城市层面的消费占比，需要另行设计抽样框、样本量与加权方法。'));
children.push(h('05 门店贡献与价格敏感性',1,true));
children.push(p('同一市场机会在不同成本结构下会产生不同结果。本节用一组透明假设展示“实收价格 × 杯量”的关系。测算参数为：每月营业 30 天，月固定成本 5.2 万元，单杯直接材料成本 6 元，渠道变动费率为实收金额的 10%。这些参数用于展示计算方法，实际项目应以租约、排班和采购报价替换。'));
children.push(...await fig(4,'图 4  日均杯量与实收价格的贡献敏感性','本报告假设测算。门店月贡献 = 日均杯量 × 30 ×（实收价格 × 90% − 6）− 52,000；单位为万元。包含列示成本，开办费、税费、折旧与总部费用需另行评估。'));
children.push(h('价格折让需要相应的增量交易',2));
children.push(p('在该假设下，实收 14 元时单杯贡献为 6.6 元，覆盖月固定成本需要约 263 杯/日；实收 16 元时单杯贡献为 8.4 元，对应约 207 杯/日。杯量相同时，提高两元实收会改变贡献空间；降价若能显著增加高峰之外的交易，也可能改善总贡献。判断依据应是增量贡献和产能约束，而非单独的销量增长。'));
children.push(table([['实收价格','单杯贡献','覆盖固定成本的日均杯量'],['12 元','4.8 元','约 362 杯'],['14 元','6.6 元','约 263 杯'],['16 元','8.4 元','约 207 杯'],['18 元','10.2 元','约 170 杯']],[2800,2800,4160]));
children.push(note('日均杯量按向上取整列示；正文中的近似量级用于解释关系。贡献测算服务经营假设比较，并非对样本品牌单店收益的估计。'));
children.push(h('06 市场进入与跟踪重点',1,true));
children.push(p('本报告建议把市场进入拆成三个可回收证据的阶段：先验证需求，再验证门店贡献，最后验证复制能力。扩张到更多商圈前，应明确哪一类用户、在哪一时段、以怎样的实收价格持续购买。试点的价值在于回答这些问题，并为后续店型和资源安排提供依据。'));
children.push(table([['阶段','核心工作','继续投入前需要的证据'],['商圈研究','客流观察、竞品交易条件、目标用户访谈','确认高频场景与现有服务缺口'],['单店试点','跟踪价格、杯量、成本与履约','贡献改善可以由可追踪经营动作解释'],['复制验证','在相近与不同商圈分别试点','识别依赖选址条件与可复制运营能力']],[1800,3500,4460]));
children.push(h('重点跟踪四类变化',2));
children.push(p('供给密度：记录有效营业门店、开业和关闭，区分真实供给增加与门店迁移。同一品牌新增网点后，观察周边老店的交易变化。若新增销售主要来自内部转移，区域整体贡献可能改善有限。'));
children.push(p('价格实现：以用户实际支付金额和企业实际承担的折扣为基础，拆分品牌补贴与平台补贴。只有持续知道谁承担成本，才能判断某种低价是否具备可持续性。监测中也应保留原价购买和套餐购买的比例。'));
children.push(p('时段效率：把早高峰、午间、下午与晚间分开观察。高峰增长如果伴随排队和超时，需要核对设备、人力和取餐安排。非高峰增长则更可能利用已有固定资源，二者的边际价值不同。'));
children.push(p('复购质量：按首次购买月份跟踪后续购买和贡献，区分优惠触达带来的短期交易与稳定习惯。以相同观察窗口比较用户批次，可以减少新客不断进入对总体复购指标的干扰。'));
children.push(h('结论适用范围',2));
children.push(p('三家披露样本呈现出供给扩张与同店压力并存的现象。可以据此提出店效和竞争密度的研究问题，但尚不足以估计全部现制咖啡市场的规模、渗透率或未来增速。具体进入策略应结合目标城市、商圈和自身成本条件完成验证，再确定店型、价格与扩张速度。'));
children.push(h('07 研究方法与资料索引',1,true));
children.push(p('研究方法为公开资料的桌面研究。量化部分以 2024 年度和相关季度披露为观察基础；消费者场景、调研问题和进入路径为本报告分析。全文涉及三类信息：企业披露事实、基于披露的计算，以及明确列示的经营假设。'));
children.push(h('数据比较原则',2));
children.push(p('门店数采用各企业披露范围和日期；瑞幸为集团口径并含海外门店，星巴克为中国地区财年口径，Tims 为中国持续经营口径。同店销售沿用企业自身定义，不把不同财季简单对齐。报告以网络、同店和运营方法组织比较，未通过简单相加推算行业总额。'));
children.push(h('主要来源',2));
for(const s of d.sources){children.push(p(`[${s.id}] ${s.publisher}  ${s.title}  ${s.date}`,{keepNext:true,children:[new TextRun({text:`[${s.id}] ${s.publisher}  ${s.title}  ${s.date}`,font,size:19,bold:true})],spacing:{before:100,after:40}}),note(s.note),new Paragraph({children:[new ExternalHyperlink({children:[new TextRun({text:'查看原始披露',style:'Hyperlink',font,size:18})],link:s.url})],spacing:{after:120}}));}
const doc=new Document({creator:'DSH',title:d.title,description:'中国现制咖啡市场调研案例',styles:{default:{document:{run:{font:{ascii:font,eastAsia:font},size:21,color:ink},paragraph:{spacing:{line:300,after:110}}}},paragraphStyles:[{id:'Title',name:'Title',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font,size:43,bold:true,color:'000000'},paragraph:{keepNext:true}},{id:'Heading1',name:'heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font,size:30,bold:true,color:'000000'},paragraph:{keepNext:true}},{id:'Heading2',name:'heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font,size:24,bold:true,color:'000000'},paragraph:{keepNext:true}}]},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:950,bottom:950,left:1073,right:1073,header:460,footer:460}}},headers:{default:new Header({children:[p('中国现制咖啡市场调研   2024 年度观察',{spacing:{after:0},children:[new TextRun({text:'中国现制咖啡市场调研   2024 年度观察',font,size:16,color:'000000'})]})]})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[new TextRun({text:'DSH  /  ',font,size:16,color:muted}),new TextRun({children:[PageNumber.CURRENT],font,size:16,color:muted})]})]})},children}]});
await fs.writeFile(office.output,await Packer.toBuffer(doc));
